IF OBJECT_ID('tempdb..#CompareTempProc') IS NOT NULL drop table #CompareTempProc

Create Table #CompareTempProc
(ID INT NOT NULL Identity(1,1),
    DataSource Varchar(255) NULL,
    ProcName Varchar(255) NULL,
    VersionNumber Varchar(255) NULL
)

--PASTE your inserts here.
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ACHN_FAMILY_ROLLUP','$Revision: 1.2.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ACHN_FORMAT','$Revision: 1.6.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ACHN_PRE_PROC','$Revision: 1.5.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_BLAD','$Revision: 1.1.2.2 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_EMAIL','$Revision: 1.9.2.17 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_EMAIL_AKIN','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_EMAIL_FFM','$Revision: 1.1.2.4 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_EMAIL_ORIN','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_LOG','$Revision: 1.10.12.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_MECB','$Revision: 1.2.4.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_MECD','$Revision: 1.8.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_MEEL','$Revision: 1.57.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_MEHE','$Revision: 1.10.6.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_MELC','$Revision: 1.2.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_MEPR','$Revision: 1.10.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_MERP','$Revision: 1.1.2.4.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_MESU','$Revision: 1.4.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_SBAD','$Revision: 1.17.6.23 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_SBADg','$Revision: 1.17.6.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_SBCS','$Revision: 1.6.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_SBEL','$Revision: 1.26.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ADD_SBSG','$Revision: 1.5.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_AKCO_FORMAT','$Revision: 1.1.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_AKDB_FORMAT','$Revision: 1.1.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_AKGR_FORMAT','$Revision: 1.8.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_AKGR_PRE_PROC','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_AKIN_PRE_PROC','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_AMER_FORMAT','$Revision: 1.7.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ARCHIVE_MMS','$Revision: 1.20.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ARCHIVE_PRE','$Revision: 1.14.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ARCHIVE_WRK','$Revision: 1.63.2.19 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ARCH_FORMAT','$Revision: 1.7.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CCPP_FORMAT','$Revision: 1.2.6.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CEME_FORMAT','$Revision: 1.12.8.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CEPL_FORMAT','$Revision: 1.6.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_BLAD','$Revision: 1.1.2.2 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_FUTURE_MEEL','$Revision: 1.14.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_FUTURE_SBCS','$Revision: 1.5.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_FUTURE_SBCSg','$Revision: 1.5.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_FUTURE_SBEL','$Revision: 1.12.2.18 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_LOGS','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_MECB','$Revision: 1.2.4.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_MECD','$Revision: 1.9.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_MEEL','$Revision: 1.100.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_MEES','$Revision: 1.6.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_MELC','$Revision: 1.2.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_MEME','$Revision: 1.13.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_MEPR','$Revision: 1.13.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_MESU','$Revision: 1.12.2.19 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBAD','$Revision: 1.26.2.25 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBAD_GB','$Revision: 1.26.2.19 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBADg','$Revision: 1.26.2.24 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBCS','$Revision: 1.29.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBCSg','$Revision: 1.29.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBEL','$Revision: 1.70.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBEM','$Revision: 1.21.6.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBRT','$Revision: 1.7.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBSB','$Revision: 1.15.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBSG','$Revision: 1.23.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHANGE_SBSG_COBRA','$Revision: 1.8.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_CSPI_MAP','$Revision: 1.18.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_DATE','$Revision: 1.10.8.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_DUP_EE_FILE','$Revision: 1.18.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_EXLUSIONS','$Revision: 1.15.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_FILES','$Revision: 1.15.2.9 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_GENDER','$Revision: 1.4.8.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_MMS_EXTRACT','$Revision: 1.4.16.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_NAME','$Revision: 1.1.8.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_PAST_ELIG','$Revision: 1.1.6.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_PHONE','$Revision: 1.4.8.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_PLAN_FFM','$Revision: 1.1.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_PLAN_INDV','$Revision: 1.1.2.2 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_PLAN_MAP','$Revision: 1.22.2.18 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_PLAN_ORIN','$Revision: 1.4.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_PRIOR_ELIG','$Revision: 1.2.6.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_SBRT','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_SBSB_ID','$Revision: 1.2.8.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_SCRUBBER_FILE','$Revision: 1.14.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_SPOUSES','$Revision: 1.15.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CHECK_SSN','$Revision: 1.4.8.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CLEANUP_PRE','$Revision: 1.5.8.2.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CLEANUP_WRK_MMS','$Revision: 1.30.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CLONE_FAMILY','$Revision: 1.8.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CLONE_MEMBER','$Revision: 1.9.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CONA_FORMAT','$Revision: 1.12.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CONVERT_SBAD_TYPE','$Revision: 1.1.2.2.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_COPY_PLAN_MAP','$Revision: 1.8.6.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_COPY_PRE_TO_WRK','$Revision: 1.14.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_COPY_RAW_DATES','$Revision: 1.27.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_COPY_RAW_MONEY','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_COPY_TP_AND_REL','$Revision: 1.12.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_COPY_WRK_TO_MMS','$Revision: 1.36.2.17 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_COUNT_MMS','$Revision: 1.12.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_COUNT_PRE','$Revision: 1.4.8.2.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_COUNT_WRK','$Revision: 1.12.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CPCO_FAMILY_ROLLUP','$Revision: 1.1.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CPCO_FORMAT','$Revision: 1.2.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CPCO_PRE_PROC','$Revision: 1.3.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CREATE_BATCH','$Revision: 1.21.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CREATE_BLEI','$Revision: 1.19.2.24 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CREATE_MEEL_SE','$Revision: 1.9.2.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CREATE_MEHE','$Revision: 1.4.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CREATE_OPT_OUT_MEEL','$Revision: 1.14.2.2.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CREATE_SBSB','$Revision: 1.6.4.2.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_COMMON_SCRUBBER','$Revision: 1.45.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_COMMON_SCRUBBERg','$Revision: 1.45.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_FAMILY_ROLLUP','$Revision: 1.54.2.21 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_IMPORT','$Revision: 1.34.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_IMPORTg','$Revision: 1.34.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_PREPARE','$Revision: 1.80.2.23 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_PREPAREg','$Revision: 1.80.2.17 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_PRE_PROC','$Revision: 1.16.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_SCRUB_FAMILY','$Revision: 1.92.2.25 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_SCRUB_FAMILYg','$Revision: 1.92.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_SCRUB_MEMBER','$Revision: 1.79.2.21 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_CTL_SCRUB_MEMBERg','$Revision: 1.79.2.18 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DCO_PRE_CHECK_CUSTOM','$Revision: 1.5.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DCO_PRE_CHECK_MEME','$Revision: 1.2.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DCO_PRE_CHECK_SBAD','$Revision: 1.2.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DCO_PRE_CHECK_SBSB','$Revision: 1.2.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DD_MEMBER_TERMG','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_DENTAL_FAMILY','$Revision: 1.16.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_DENTAL_MEMBER','$Revision: 1.7.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_CLONE_FAMILY','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_CLONE_MEMBER','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_DR_FAMILY','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_DR_MEMBER','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_FAMILY','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_MEMBER','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_MEMBER_EMBEDDED_MAIN_IN','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_MEMBER_STANDALONE_CLONE_FROM_FACETS_IN','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_MEMBER_STANDALONE_CLONE_IN','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_MEMBER_STANDALONE_MAIN_D','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_MEMBER_STANDALONE_MAIN_UP','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_MEMBER_TERM','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_DUAL_D_RUN_STEPS','$Revision: 1.92.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EENROLL_DELETE','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EENROLL_LOAD','$Revision: 1.1.2.3 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EENROLL_LOAD_CUSTOM_DATA','$Revision: 1.1.2.5 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EENROLL_LOAD_MEME','$Revision: 1.1.2.17 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EENROLL_LOAD_SBSB','$Revision: 1.1.2.6 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EENROLL_PRE_DELETE','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EENROLL_PRE_LOAD','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EFT_ENROLL','$Revision: 1.6.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EOCD_FAMILY_ROLLUP','$Revision: 1.1.4.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EOCD_FORMAT','$Revision: 1.4.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EOCD_PRE_PROC','$Revision: 1.4.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EOC_PRE_CHECK_SBSB','$Revision: 1.1.2.1.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EODD_FAMILY_ROLLUP','$Revision: 1.2.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EODD_FORMAT','$Revision: 1.3.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EODD_GET_TRANS_PLAN','$Revision: 1.4.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EODD_PREPARE_END','$Revision: 1.7.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EODD_PREPARE_ENDg','$Revision: 1.7.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EODD_PRE_PROC','$Revision: 1.4.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EODM_GET_TRANS_PLAN','$Revision: 1.1.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EODM_PREPARE_END','$Revision: 1.4.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EOD_PRE_CHECK_SBSB','$Revision: 1.1.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_EXTRACT_BROKER','$Revision: 1.3.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FAMILY_PLAN_DCO','$Revision: 1.1.2.5 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FAMILY_PLAN_FFM','$Revision: 1.4.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FAMILY_PLAN_INDV','$Revision: 1.1.2.5 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FAMILY_PLAN_OEBB','$Revision: 1.16.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FCTC_FAMILY_ROLLUP','$Revision: 1.1.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FCTC_FORMAT','$Revision: 1.4.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FCTC_PRE_PROC','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_CREATE_DEP_TERM','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_FAMILY_ROLLUP','$Revision: 1.2.2.25 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_FORMAT','$Revision: 1.1.2.23 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_PASSIVE_TERMS','$Revision: 1.1.2.7 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_PRE_CHECK_MEME','$Revision: 1.1.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_PRE_CHECK_SBSB','$Revision: 1.3.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_PRE_GLOBAL_TERMS','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_PRE_PROC','$Revision: 1.1.2.9 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_TERM_MEES','$Revision: 1.2.2.4 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_TERM_MEHE','$Revision:  $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FFM_TERM_MESU','$Revision: 1.3.2.4 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FORMAT_ADDRESS','$Revision: 1.7.2.3.4.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FORMAT_FIRST_NAME','$Revision: 1.3.2.2.4.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FORMAT_KPAK','$Revision: 1.1.2.3 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FORMAT_LAST_NAME','$Revision: 1.1.2.1.4.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FORMAT_PHONE','$Revision: 1.3.8.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FORMAT_SHEE','$Revision: 1.2.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_FORMAT_VAFF','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_ELIG_DATES','$Revision: 1.53.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_FACETS_ELIG','$Revision: 1.8.12.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_FACETS_ELIGg','$Revision: 1.8.12.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_FI_COUNTERS','$Revision: 1.3.4.19 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_MEME','$Revision: 1.12.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_MEME_EFF_DT','$Revision: 1.31.6.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_MEME_EFF_DTg','$Revision: 1.31.6.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_NUM_ELIG_DAYS','$Revision: 1.1.2.4 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_PLAN_ELIG','$Revision: 1.3.4.1.4.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_PLAN_MAP','$Revision: 1.11.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_SBSB','$Revision: 1.22.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_SBSB_EFF_DT','$Revision: 1.15.6.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GET_TRANS_PLAN','$Revision: 1.7.6.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_GUNA_FORMAT','$Revision: 1.11.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_HADA_FORMAT','$Revision: 1.10.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_HALT_FORMAT','$Revision: 1.3.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_HAS_ELIGIBILITY','$Revision: 1.2.4.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_HAS_ELIGIBILITYG','$Revision: 1.2.4.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_HAS_ELIGIBILITYg','$Revision: 1.2.4.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_HUBB_FORMAT','$Revision: 1.18.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_IBUP_FORMAT','$Revision: 1.1.4.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_IBUP_PRE_CHECK_MEME','$Revision: 1.1.2.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_IBUP_PRE_CHECK_SBSB','$Revision: 1.1.4.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ICHN_FAMILY_ROLLUP','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ICHN_FORMAT','$Revision: 1.8.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ICHN_PRE_PROC','$Revision: 1.4.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_IMPLICIT_TERMS','$Revision: 1.61.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_ADD_CHANGE_MEPR','$Revision: 1.1.2.3 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_CREATE_DEP_TERM','$Revision: 1.1.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_FAMILY_ROLLUP','$Revision: 1.1.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_FORMAT','$Revision: 1.1.2.5 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_POST_MMS','$Revision: 1.1.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_PRE_CHECK_MEME','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_PRE_CHECK_MEME_POST','$Revision: 1.1.2.2 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_PRE_PROC_POST','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_SET_CLASS_DENT','$Revision: 1.2.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_INDV_UPDT_EMBED_DENT','$Revision: 1.2.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_IS_EXCLUDED','$Revision: 1.17.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_JCCO_FAMILY_ROLLUP','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_JCCO_FORMAT','$Revision: 1.3.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_JCCO_PRE_PROC','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_KNLC_FORMAT','$Revision: 1.7.6.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_LGCY_FORMAT','$Revision: 1.9.8.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_LOAD_834_SOURCE','$Revision: 1.7.12.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_LOAD_834_SOURCE_KR','$Revision: 1.7.12.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_LOAD_EXCL','$Revision: 1.1.2.5 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_LOAD_GSCP','$Revision: 1.8.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_LOAD_GSCP_OEBB','$Revision: 1.29.2.29 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_LOAD_GSCPg','$Revision: 1.8.2.18 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_LOG_FUTURE_EVENTS','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_LOG_FUTURE_RI','$Revision: 1.2.8.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_MAP_MEME_RE','$Revision: 1.1.2.7 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_MCCC_FORMAT','$Revision: 1.1.2.2 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_MEMBER_PLAN_INDV','$Revision: 1.1.2.3 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_MEPR','$Revision: 1.13.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_MODA_FORMAT','$Revision: 1.11.4.8 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_NIKC_FORMAT','$Revision: 1.1.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_NIKE_FORMAT','$Revision: 1.5.12.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OEBB_ADD_CHANGE_MEPR','$Revision: 1.6.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OEBB_FAMILY_ROLLUP','$Revision: 1.3.6.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OEBB_FORMAT','$Revision: 1.10.2.21 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OEBB_PREPARE_END','$Revision: 1.7.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OEBB_PRE_CHECK_MEME','$Revision: 1.16.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OEBB_PRE_CHECK_SBEL','$Revision: 1.10.4.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OEBB_PRE_CHECK_SBSB','$Revision: 1.16.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OEBB_PRE_PROC','$Revision: 1.22.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OEBB_SET_FAM_MEM_ID','$Revision: 1.2.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OHPD_FAMILY_ROLLUP','$Revision: 1.11.6.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OHPD_FORMAT','$Revision: 1.8.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OHPD_PRE_PROC','$Revision: 1.8.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OHP_PRE_CHECK_CUSTOM','$Revision: 1.2.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OHP_PRE_CHECK_MEME','$Revision: 1.5.4.1.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OHP_PRE_CHECK_SBSB','$Revision: 1.5.4.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_OHSU_FAMILY_ROLLUP','$Revision: 1.1.2.2 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ORCO_FORMAT','$Revision: 1.2.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ORIN_PRE_PROC','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PACS_FORMAT','$Revision: 1.9.6.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PASSIVE_FFMPASS','$Revision: 1.1.2.8 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PASSIVE_FFMPASS_SHOWONLY','$Revision: 1.1.2.8 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PBHS_FORMAT','$Revision: 1.5.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PBHS_PRE_CHECK_SBEL','$Revision: 1.2.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PBHS_PRE_CHECK_SBSB','$Revision: 1.4.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PBHS_PRE_FILE','$Revision: 1.6.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PBHS_SET_FAM_MEM_ID','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PEBB_FORMAT','$Revision: 1.1.2.4.4.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PEBB_PRE_CHECK_SBSB','$Revision: 1.1.2.6.4.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PEBB_PRE_FILE','$Revision: 1.18.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PEBB_PRE_PROC','$Revision: 1.6.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PEBB_SET_FAM_MEM_ID','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PERS_FORMAT','$Revision: 1.7.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PHJC_FAMILY_ROLLUP','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PHJC_FORMAT','$Revision: 1.4.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PHJC_PRE_PROC','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PORT_FORMAT','$Revision: 1.6.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_POST_MMS','$Revision: 1.1.2.2 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_ACHN','$Revision: 1.19.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_AKGR','$Revision: 1.5.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_AKIN','$Revision: 1.10.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_CEME','$Revision: 1.6.6.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_CPCO','$Revision: 1.8.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_EOCD','$Revision: 1.14.2.17 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_EODD','$Revision: 1.9.2.18 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_FCTC','$Revision: 1.13.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_FFM','$Revision: 1.3.2.19 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_ICHN','$Revision: 1.10.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_INDV','$Revision: 1.1.2.8 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_ITGS','$Revision: 1.1.2.6 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_JCCO','$Revision: 1.14.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_LGCY','$Revision: 1.6.6.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_MUNI','$Revision: 1.7.6.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_OEBB','$Revision: 1.28.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_OHPD','$Revision: 1.13.2.18 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_ORIN','$Revision: 1.6.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_PHJC','$Revision: 1.11.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_PSCO','$Revision: 1.5.2.21 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_SAIF','$Revision: 1.15.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_TCHP','$Revision: 1.6.2.22 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_TCMC','$Revision: 1.15.2.21 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_WVCH','$Revision: 1.17.2.21 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PREPARE_YCCO','$Revision: 1.7.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PRE_CHECK_DUPS','$Revision: 1.5.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PRE_CHECK_MEME','$Revision: 1.6.2.3.2.17 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PRE_CHECK_SBSB','$Revision: 1.10.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PRE_PROC','$Revision: 1.6.2.18 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PS1_VALIDATE_BATCH','$Revision: 1.3.2.19 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PSCO_FAMILY_ROLLUP','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PSCO_FORMAT','$Revision: 1.3.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PSCO_PRE_PROC','$Revision: 1.2.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PSUM_FORMAT','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PSUM_SET_FAM_MEM_ID','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PSYN_FORMAT','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PSYN_SET_FAM_MEM_ID','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PTRI_FORMAT','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_PTRI_SET_FAM_MEM_ID','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_RECORD_INCLUSION','$Revision: 1.15.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_RECO_FORMAT','$Revision: 1.2.6.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ROLLUP_FAMILY','$Revision: 1.60.4.28 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_ROLLUP_FAMILY_KR','$Revision: 1.60.4.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SAIF_FORMAT','$Revision: 1.16.6.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SAMA_FORMAT','$Revision: 1.1.6.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SBAD_CHANGE_ADDR','$Revision: 1.13.6.26 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SBAD_CHANGE_ADDRg','$Revision: 1.13.6.19 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCHN_FORMAT','$Revision: 1.1.2.2 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_ACHN','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_AKIN','$Revision: 1.8.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_CPCO','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_EOCD','$Revision: 1.6.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_EODD','$Revision: 1.2.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_FCTC','$Revision: 1.2.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_FFM','$Revision: 1.3.2.19 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_ICHN','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_INDV','$Revision: 1.1.2.6 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_JCCO','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_OEBB','$Revision: 1.14.8.4 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_OHPD','$Revision: 1.7.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_ORCO','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_ORIN','$Revision: 1.3.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_PERS','$Revision: 1.2.8.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_PHJC','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_PSCO','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_TCHP','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_TCMC','$Revision: 1.2.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_WVCH','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAMILY_YCCO','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_FAM_MEDICAID','$Revision: 1.1.2.2 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_MEMBER_INDV','$Revision: 1.1.2.1 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_MEMBER_LGCY','$Revision: 1.3.6.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_MEMBER_NIKE','$Revision: 1.4.12.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_MEMBER_OEBB','$Revision: 1.21.4.21 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_MEMBER_PBHS','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_MEMBER_PEBB','$Revision: 1.11.6.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_MEMBER_PTRI','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SCRUB_MEMBER_WSRX','$Revision: 1.6.2.19 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SET_EFF_DT','$Revision: 1.25.2.33 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SET_FILE_MANAGMENT','$Revision: 1.7.2.17 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SET_GRGR_ID','$Revision: 1.4.16.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SET_HSA_PLANS','$Revision: 1.4.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SET_MEME_ID_NAME','$Revision: 1.5.8.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SET_SBCS_FFM','$Revision: 1.2.2.20 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SET_SBCS_INDV','$Revision: 1.1.2.4 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SET_SBCS_ORIN','$Revision: 1.1.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SHDP_FORMAT','$Revision: 1.3.4.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SUPPRESS_MEEL','$Revision: 1.30.6.21 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SUPPRESS_SUBSC','$Revision: 1.9.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_SWAP_SBSB_MEME','$Revision: 1.7.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TCHP_FAMILY_ROLLUP','$Revision: 1.1.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TCHP_FORMAT','$Revision: 1.2.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TCHP_PRE_PROC','$Revision: 1.2.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TCMC_FAMILY_ROLLUP','$Revision: 1.1.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TCMC_FORMAT','$Revision: 1.3.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TCMC_PRE_PROC','$Revision: 1.3.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TERM_MEEL','$Revision: 1.29.2.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TERM_OLD_PLAN','$Revision: 1.10.2.18 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TERM_OLD_PLAN_INDV','$Revision: 1.1.2.4 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TERM_OLD_PLANg','$Revision: 1.10.2.17 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TERM_SBEL','$Revision: 1.26.2.17 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TERM_SBEM','$Revision: 1.8.2.1.4.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TP_INSERT','$Revision: 1.49.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TRANS_PLAN_MEEL','$Revision: 1.36.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_TRANS_PLAN_SBEL','$Revision: 1.37.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_UNOP_FORMAT','$Revision: 1.2.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_UPDATE_BLCO','$Revision: 1.7.2.39 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_UPDATE_IN_CH','$Revision: 1.6.4.15 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_UPDT_EMBED_DENT','$Revision: 1.2.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_VAWT_FORMAT','$Revision: 1.7.8.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_WAGR_PRE_CHECK_MEME','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_WAGR_PRE_CHECK_SBSB','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_WDOC_FORMAT','$Revision: 1.1.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_WDOM_FORMAT','$Revision: 1.1.2.11 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_WSRX_FORMAT','$Revision: 1.16.4.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_WVCH_FAMILY_ROLLUP','$Revision: 1.1.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_WVCH_FORMAT','$Revision: 1.7.2.16 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_WVCH_PRE_PROC','$Revision: 1.5.2.12 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_YCCO_FAMILY_ROLLUP','$Revision: 1.1.2.14 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_YCCO_FORMAT','$Revision: 1.2.2.13 $')
Insert #CompareTempProc Values ('Dev03','ODS_SP_EI_YCCO_PRE_PROC','$Revision: 1.3.2.12 $')

IF OBJECT_ID('tempdb..#TempProc') IS NOT NULL drop table #TempProc

Create Table #TempProc
(ID INT NOT NULL Identity(1,1),
    ProcName Varchar(255) NULL,
    VersionNumber Varchar(255) NULL
)

--Loop through All of the ODS_EI_ Procedures     
--PERFORM ACTIONS
DECLARE curRequest INSENSITIVE Cursor FOR 

Select Name as ProcName
from sysobjects as A
Where Name like 'ODS_SP_EI_%'	and xtype = 'P'
Order by Name

Open curRequest

DECLARE @ProcName Varchar(255)

While 1 = 1
    BEGIN
	   Fetch NEXT FROM curRequest INTO @ProcName
	   IF (@@FETCH_STATUS <> 0)
			 Break
			
               Insert #TempProc
               SELECT @ProcName, Convert(Varchar(255), value)
	          FROM sys.fn_listextendedproperty ('SourceCodeVersion', 'schema', 'dbo', 'procedure', @ProcName, default, default)
    END

CLOSE curRequest
DEALLOCATE curRequest

Select B.ProcName, A.VersionNumber as STG3_Version, B.VersionNumber as ST2_Version
from #CompareTempProc as A
    LEFT JOIN #TempProc as B
        On A.ProcName = B.ProcName
Where A.VersionNumber <> B.VersionNumber
Order by B.ProcName
